### ISSUE TITLE
Layout: style help text

### ISSUE THREAD

**Issue by sergei-maertens** [maykinmedia/zds-token-issuer#3]
I've added the help text of the text input to the template (sniplates library), which is currently unstyled.

The help text should be below the text input box and be a bit more visually appealing (I'm thinking correct font, slightly lighter font color than the main text).

See screenshot - I'm referring to the green box. The arrow describes where the help text should be displayed.

![token-issuer-1](https://user-images.githubusercontent.com/5518550/49070703-9d84a980-f22c-11e8-9a97-dd1ff27c74f8.png)

**Comment by svenvandescheur** [comment]
https://github.com/maykinmedia/zds-token-issuer/pull/6
