### ISSUE TITLE
UX: copy-paste behaviour is annoying

### ISSUE THREAD

**Issue by sergei-maertens** [maykinmedia/zds-token-issuer#4]
On both pages, the copy-paste behaviour is annoying. When you double-click the value on the right to be able to paste it in Postman or other tools, the label on the left is also selected. This is unwanted - only the right-hand side should be selected and copied.

Additionally, a simple 'copy to clipboard' button next to the value (just like Github has for the clone URL) would be convenient.

Pink area in the screenshot.

![token-issuer-1](https://user-images.githubusercontent.com/5518550/49070703-9d84a980-f22c-11e8-9a97-dd1ff27c74f8.png)

**Comment by svenvandescheur** [comment]
https://github.com/maykinmedia/zds-token-issuer/pull/6
