### ISSUE TITLE
UX/UI: JWT generation is unclear/messy

### ISSUE THREAD

**Issue by sergei-maertens** [maykinmedia/zds-token-issuer#5]
The layout of the page where you can generate the JWT is too confusing - various areas are marked.

**pink box**

The entire box containing the HTTP header name and value is not separated well enough from the client ID/secret inputs. I think this should have it's own box/background and be styled in its entirity as 'code'.

**orange oval**

This is the same selection issue as in #4 - double clicking the value should not lead to the label being copied.

**green box**

* a 'copy-to-clipboard' button here would go a long way as well, may be exactly the same as #4 
* we've noticed that people only copy parts - i.e. it's unclear that the value is a lot longer. Can we get rid of the horizontal scroll bar and display the entire value? line-wrap is fine - as long as no newlines are introduced when copying the value
* nice to have: https://jwt.io/ displays the JWT 'syntax highlighted' - i.e. the header, payload and signature have their own colours and are nicely formatted. It would be great if we could get a similar representation.

![token-issuer-2](https://user-images.githubusercontent.com/5518550/49071037-4df2ad80-f22d-11e8-9fa2-280cc73f8c99.png)

**Comment by svenvandescheur** [comment]
https://github.com/maykinmedia/zds-token-issuer/pull/6
